### ISSUE TITLE
Protocol extensions wrapped 

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#10]
- [ ] screenshooter
- [ ] gamma-control
- [x] server decoration
- [ ] gtk-primary-selection
- [ ] idle
- [ ] xwayland-keyboard-grab

**Comment by alexander-smoktal** [comment]
@Timidger, what are you gonna do with `wl_display` handle? A lot of wlr functions accept raw pointer.

**Comment by alexander-smoktal** [comment]
Inside rootston for example

**Comment by Timidger** [comment]
You'll need provide an explicit example where you think there might be an issue.

What will probably happen is that we'll keep the compositor as the "owner" of the `wl_display` handle and pass out weak references via `Rc`/`Weak`. If that's too complicated, we can change the structure of the library so that the `wl_display` has shared ownership properties, though I want to make sure that once it's been cleaned up by Wayland we can't use it anymore.

Would be prudent to go through [the wayland-rs library](https://github.com/Smithay/wayland-rs/) to see how they do it, they heavily abstract the server side and that might help us figure out our design.

**Comment by alexander-smoktal** [comment]
I mean, do we wrap wl_display? Because to develop safe wrappers for all functions, we have to to that. If so, do we use some wrapper from `crates.io`, or develop internal wrapper?

**Comment by Timidger** [comment]
If the `wl_display` needs to be passed explicitly to some wlroots functions, then yes making a wrapper would make it easier to manage. It should be simple to make our own, since it's just like all the other handles we create we can just create it like that (e.g a `new` that calls the wayland function to get the pointer (need to ensure you can call it multiple times, you might not be able to), and on drop call the cleanup function).

Currently, we just store it in the `Compositor` struct as one of the fields. I was planning on exposing it eventually, but mostly so the user of the lib can use it to (unsafely) extend wlroots-rs if necessary.

**Comment by Timidger** [comment]
Closing in favour of [using a milestone to keep track of what's left to do](https://github.com/swaywm/wlroots-rs/milestone/1)
