### ISSUE TITLE
Idle Protocol

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#100]
A wrapper around the idle optional Wayland extension.

[Here is the protocol](https://github.com/swaywm/wlroots/blob/master/protocol/idle.xml) and [here is the relevant header file to wrap](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/idle.h).

**Comment by SethBarberee** [comment]
Working on this right now. Should hopefully have a PR done by the end of the week.
