### ISSUE TITLE
Wrap wlr_xcursor_manager_theme

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#133]
# XCursorManager
## getters
- [ ] `name`, return `String`, see ::utils for conversion helpers
- [ ] `size`, return `u32`
- [ ] `scaled_themes`, return `Vec<XCursorManagerTheme>`
  * This will require using either the macro in `macros.rs` to iterate over the list (it emulates the macro in C to iterate the list) or to call the functions directly
  * This will also require adding a bound on the theme potentially, depending on if you could access freed memory by destroying the manager but keeping the theme that was generated from it around.
## functions
- [ ] `fn new(name: String, size: u32) -> XCursorManager`, wraps the create function, panic if the result is null.
- [ ] `impl Drop for XCursorManager { ... }`, call `wlr_xcursor_manager_destroy`
- [ ] `load`, taking a `libc::c_float` scale, return a `libc::c_int`. Require `&mut self` since it does internal mutation and we need to be explicit about that.
- [ ] `get_xcursor`
- [ ] `set_cursor_image`

# XCursorManagerTheme
## getters
- [ ] `scale`, return `libc::c_float`
- [ ] `theme`, return `XCursorTheme`
- [ ] derive standard traits (`Debug`, `Eq`, `PartialEq`)

These need to be getters, because we can't expose the raw pointer directly, because derefering a raw pointer requires an unsafe block.

A good module to look at is [the xcursor one](https://github.com/swaywm/wlroots-rs/blob/master/src/types/cursor/xcursor.rs), which you will also be using since it returns it for `get_xcursor`. The most complicated thing is the `PhantomData`, which is documented [here](https://doc.rust-lang.org/std/marker/struct.PhantomData.html). Basically they are a way to say "you own this, but you can only own it this long".

Bonus points demonstrate this works by replacing the old way in `examples/pointer.rs`

**Comment by acrisci** [comment]
Ok I think I fnally know enough rust to get started on this.
