### ISSUE TITLE
Make libcap, systemd, elogind optional

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#139]
Currently we just use the defaults, but this is incorrect on e.g non-systemd systems.

To correspond to wlroots, there should be a feature flag to enable each one and they should all be on by default. 

If they cannot be found in the system (TODO How do we do this), then we do not add them to the linking stage.

Of course, if we are not statically linking then these feature flags aren't necessary.

**Comment by psychon** [comment]
> If they cannot be found in the system (TODO How do we do this)

wlroots uses meson, which uses pkg-config for finding optional dependencies. I saw that there is a pkg-config crate that could be used in `build.rs` in a similar way (however, I do not know how/if `build.rs` can influence the built rust code to inform it about "FOO is unavailable").

**Comment by Timidger** [comment]
> (however, I do not know how/if build.rs can influence the built rust code to inform it about "FOO is unavailable").

It can use that information to decide what flags to emit, which will stop the error from happening

**Comment by psychon** [comment]
Ah, okay, I thought that the presence of these libraries also influences the API of wlroots, which means that the API that wlroots-rs wraps must change. If that's not the case, then this is indeed easier.

**Comment by Timidger** [comment]
I don't believe it does, but if so you can add checks in the code to handle that.
