### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by SolarAquarion** [swaywm/wlroots-rs#142]
[218/320] Compiling C object 'rootston/rootston@exe/desktop.c.o'.
FAILED: rootston/rootston@exe/desktop.c.o 
ccache cc  -Irootston/rootston@exe -Irootston -I../../../../../wlroots-rs/wlroots-sys/wlroots/rootston -Iinclude -I../../../../../wlroots-rs/wlroots-sys/wlroots/include -I/usr/include/libdrm -I/usr/include/pixman-1 -I/home/solaraquarion/build/way-cooler-git/src/way-cooler-git/target/release/build/wlroots-sys-3d54937d32ce8f2f/out -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O0 -g -Wno-unused-parameter '-DWLR_SRC_DIR="/home/solaraquarion/build/way-cooler-git/src/way-cooler-git/wlroots-rs/wlroots-sys/wlroots"' -DWL_HIDE_DEPRECATED -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -MD -MQ 'rootston/rootston@exe/desktop.c.o' -MF 'rootston/rootston@exe/desktop.c.o.d' -o 'rootston/rootston@exe/desktop.c.o' -c ../../../../../wlroots-rs/wlroots-sys/wlroots/rootston/desktop.c
../../../../../wlroots-rs/wlroots-sys/wlroots/rootston/desktop.c: In function ‘view_at’:
../../../../../wlroots-rs/wlroots-sys/wlroots/rootston/desktop.c:603:12: error: ‘_surface’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   *surface = _surface;
   ~~~~~~~~~^~~~~~~~~~
cc1: all warnings being treated as errors
[219/320] Generating 'examples/screenshot@exe/wlr-input-inhibitor-unstable-v1-client-protocol.h'.

**Comment by Timidger** [comment]
For future readers: Update your compiler version, as this is a wlroots issue
