### ISSUE TITLE
Type mismatch in src/types/input/input_device.rs:28

### ISSUE THREAD

**Issue by TapioT** [swaywm/wlroots-rs#148]
The compilation of wlroots-rs master fails because of mismatched types:
   Compiling wlroots v0.0.0 (file:///home/tallgren/git/way-cooler/wlroots-rs)
error[E0308]: mismatched types
  --> src/types/input/input_device.rs:28:18
   |
27 |     pub fn vendor(&self) -> c_int {
   |                             ----- expected `i32` because of return type
28 |         unsafe { (*self.device).vendor }
   |                  ^^^^^^^^^^^^^^^^^^^^^ expected i32, found u32

In the file wlroots/include/wlr/types/wlr_input_device.h, device is defined as unsigned int, so the return type of vendor should be c_uint

**Comment by Timidger** [comment]
This should be fixed now.
