### ISSUE TITLE
Instructions on how to build examples

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots-rs#150]
Hi,

I don't see the examples being built on `cargo build` and there aren't any instructions in the readme on how to build them.

How do you have in mind to build the examples? We should add some documentation for this.

**Comment by Timidger** [comment]
Hey acrisci.

To build examples using cargo you use `cargo build --examples`.

Feel free to open a pr to add this info to the README, but this is fairly well known across the Rust ecosystem.
