### ISSUE TITLE
Remove wl_shell

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots-rs#178]
We've never seen a correct wl_shell implementation anywhere in the wild and the consensus seems to be among Wayland developers that it is not possible to create a fully-featured shell client with this protocol. It is officially deprecated by the Wayland project and has recently been [dropped by sway](https://github.com/swaywm/sway/issues/1692).

**Comment by Timidger** [comment]
Very fine by me

**Comment by Timidger** [comment]
Fixed with #185
