### ISSUE TITLE
SystemTime is not monotonic

### ISSUE THREAD

**Issue by acrisci** [swaywm/wlroots-rs#180]
Some wlroots functions use monotonic time, like sending frame done to surfaces and sending seat events that don't come directly from the input device.

From [SystemTime](https://doc.rust-lang.org/std/time/struct.SystemTime.html):

> Distinct from the Instant type, this time measurement is not monotonic.

From [Instant](https://doc.rust-lang.org/std/time/struct.Instant.html) type:

> Instants are opaque types that can only be compared to one another. There is no method to get "the number of seconds" from an instant.

I don't believe there is any way to get monotonic time as a number of milliseconds from the Rust standard library.

What's needed is the result of `clock_gettime()` with `CLOCK_MONOTONIC` for these cases.

Should we add a utility function to call `clock_gettime()` with ffi or is there any way to get this value from Rust?

**Comment by acrisci** [comment]
This should use monotonic time.

https://github.com/swaywm/wlroots-rs/blob/2349438247ded11c5df8d89afe111bc343275b71/examples/xdg_shell_v6_test.rs#L302-L307

**Comment by Timidger** [comment]
Yes we can use [the libc wrapper](https://doc.rust-lang.org/1.9.0/libc/fn.clock_gettime.html).

Utility functions to make this easier for the library user will be necessary. They should live in `utils.rs`
