### ISSUE TITLE
Initialisation problem when using nanovg

### ISSUE THREAD

**Issue by green7ea** [swaywm/wlroots-rs#203]
I'm trying to build a simple compositor that uses `wlroots-rs` and `nanovg-rs`. Using `gles2`, I'm able to build a nanovg context after doing `CompositorBuilder::build_auto`. I can't initialise nanovg before doing `build_auto` since it needs a valid gl context to work.

I would like the `OutputManager` I create to have access to the nanovg context so that it can pass it on to each `Output` where it can be used while rendering. I cannot pass it on when I construct the `OutputManager` since the gl context is not valid then. Once I've built the compositor, I've no way to access the `output_manager` as it is private and so cannot give it the newly created nanovg context.

It's a bit of a chicken and egg problem. Maybe I'm missing something obvious and if that's the case I'm sorry for taking up your time.

**Comment by Timidger** [comment]
Hi there.

Accessing the `OutputManager` after passing it to the builder isn't really possible outside of the callbacks. We lose all the information about the struct becomes it becomes a boxed trait, so there's no real way to get your `OutputManager` struct back out.

As an alternative, I suggest looking at what I did [in the xdg shell example](https://github.com/swaywm/wlroots-rs/blob/master/examples/xdg_shell_v6_test.rs#L276). The `Seat` is a similar problem where we want to init it at the beginning and then not touch it. We store a `Seat` in the global compositor state, which _is_ possible to access from `Compositor` as shown there. Then we can use it afterwards.

I suggest moving your `nanovg::Context` to the struct you pass to `build_auto`. It also gives you greater flexibilty to access the context in callbacks other than the output (though you probably won't be doing that anyways).

**Comment by green7ea** [comment]
Thank you for the quick reply, suggestion and great project. I have tried what you suggested and it works wonderfully.
