### ISSUE TITLE
No way to access session (from Backend)

### ISSUE THREAD

**Issue by buffet** [swaywm/wlroots-rs#245]
I might be missing something, but it looks like the only way to access the current session (e.g. to change_vt) seems to be `wlr_session_change_vt(wlr_backend_get_session(drm_backend.as_ptr()), vt)`, which is unsafe and only works on the DRM backend as the others don't have a way to get the backend or the session (or rather, it's private).
There also doesn't seem to be a way to access the session object in the Compositor.

I'd suggest adding the `Backend::Drm::session()` and `Backend::Multi::wlr_multi_get_session()` from #193 back in.

**Comment by buffet** [comment]
Ah, I only checked before 0.2.4, since that's what I'm using currently. I should probably switch to a submodule.

What's the way to access it in 0.2.4?

**Comment by Timidger** [comment]
[Get the backend](http://way-cooler.org/docs/wlroots/compositor/struct.Compositor.html#method.backend_mut). [Get the Session](http://way-cooler.org/docs/wlroots/backend/enum.Backend.html#method.get_session).

A submodule is probably for the best, as there's large parts that need to be fleshed out. Realize I'm going to break a lot of things though, as wlroots will break things and I need to still balance the safety and ergonomics of the library which means breakage. I will try to ensure all breaking PRs has the breaking tag.

FYI I have the docs built semi-regularly [here](http://way-cooler.org/docs/wlroots/) (eventually that will be automated to be master probably).

Also I have a book I'm starting to write on how to make a wayland compositor [here](http://way-cooler.org/book/index.html). If you find it useful I appreciate feedback as it's something I'm going to be focusing on this year.

**Comment by buffet** [comment]
Got you, thanks a lot.

I'll close if I find it in this app.
