### ISSUE TITLE
Modifiers in xdg_shell do not work

### ISSUE THREAD

**Issue by saboteurspk** [swaywm/wlroots-rs#290]
I was trying the xdg_shell_v6_test example. But modifier keys (shift, etc.) do not work for weston-terminal that could be opened by pressing F1 key.
I was looking into keyboard handling in Sway and it seems, that there are two lines missing in keyboard handling:

```
#[dehandle] let keyboard = state.keyboard.clone().unwrap();
seat.set_keyboard(keyboard.input_device());
```

But even after this  the modifier keys do not work. Any help? :) Thank You

**Comment by Timidger** [comment]
Yep they don't work because when they example was made it was just a quick test.

There should be a call to send_modifiers in the on key callback. That tells the client what modifiers are currently being used.

**Comment by saboteurspk** [comment]
Thank You, works like a charm, I've done a PR for this.
