### ISSUE TITLE
XCursor

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#34]
~Mostly done, few things left to do.~

The interface has changed, and now it must be re-supported.

## Safety
* Double check that `images` slice is correct and that the lifetimes can't lead to unsafety.

## Functions
- [ ] `image_count`
- [ ] `name` Return `String`
- [ ] `total_delay` Document it's the length of the animation in ms

**Comment by alexander-smoktal** [comment]
@Timidger, they've added `wlr_xcursor_manager`. Probably needs another issue.

**Comment by Timidger** [comment]
Yep I saw that the latest master breaks this. I'll have to rethink how to structure xcursor then, since I had tied the lifetime to the Wayland cursor struct. Thanks for updating this issue
