### ISSUE TITLE
ScreenShooter extension

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#97]
A wrapper around the screen shooter optional Wayland extension.

[Here is the protocol](https://github.com/swaywm/wlroots/blob/master/protocol/screenshooter.xml) and [here is the relevant header file to wrap](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_screenshooter.h).

**Comment by SethBarberee** [comment]
In #247, you mentioned exposing callbacks for this protocol. Could you elaborate which ones you mean, @Timidger? I've added close to the same code for screenshooter as I did for gamma control so far.

**Comment by Timidger** [comment]
Ah interesting, I didn't actually look at the header file very closely. You don't need to expose anything since it seems wlroots takes care of taking the output pixels out and giving them to the client on behalf of the compositor. So ignore what I said in that issue :smile:
