### ISSUE TITLE
GammaControl extension

### ISSUE THREAD

**Issue by Timidger** [swaywm/wlroots-rs#98]
A wrapper around the gamma control optional Wayland extension.

[Here is the protocol](https://github.com/swaywm/wlroots/blob/master/protocol/gamma-control.xml) and [here is the relevant header file to wrap](https://github.com/swaywm/wlroots/blob/master/include/wlr/types/wlr_gamma_control.h).

**Comment by SethBarberee** [comment]
I was looking into implementing this. From what I was reading, is it safe to use the server_decoration implementation in wlroots-rs as a nice basis? If so, I can try to get something coded up and PR'd pretty soon, I think.

**Comment by Timidger** [comment]
@SethBarberee yep! That's a good basis for writing this, it'd look probably pretty similar.
